### ISSUE TITLE
printscreen

### ISSUE THREAD

**Issue by rezafaizarahman** [tealinuxos/lapor#1]
Ringkasan : Tombol printscreen tidak berjalan dengan normal

Langkah :
- Tekan tombol printscreen di keyboard, tidak muncul apa-apa
- Diharapkan : Muncul gambar di folder pictures/home
- Yang muncul : Tidak muncul apa-apa

Error : Tidak terdapat error

**Comment by baiquniinside** [comment]
tes tes first time in github
