### ISSUE TITLE
blackscreen

### ISSUE THREAD

**Issue by farasyidk** [tealinuxos/lapor#10]
saat saya booting tealinux 7 setelah loading daun tea, di layar hanya muncul cursor. tapi saya tekan win+r muncul pencarial, saya coba membuka aplikasi firefox bisa.
mohon solusinya. trims
sya printscreen
![blackscreen](https://cloud.githubusercontent.com/assets/7539791/14225391/030b20b8-f8b1-11e5-82ac-38ce18c2fae2.png)
dan muncul pesan eror berikut
![pesan-eror](https://cloud.githubusercontent.com/assets/7539791/14225403/846e5b02-f8b1-11e5-947a-b8e0777e6ac7.png)

**Comment by mnirfan** [comment]
terima kasih telah melapor.
kalau boleh tahu dapat media instalasi dari mana?

**Comment by farasyidk** [comment]
saya mendapatkannya dari tealinuxos.org, lebih tepatnya http://pinguin.dinus.ac.id/iso/tealinuxos/TeaLinuxOS-7.1-i386.iso
blackscreen itu langsung muncul, pdahal saya belum memilih live cd..

**Comment by mnirfan** [comment]
Coba booting ke bootable media instalasi TeaLinuxOS 7 anda, saat muncul icon keyboard di bawah tekan sembarang tombol sehingga muncul menu.  Pilih "Try TeaLinuxOS without installing".
Seharusnya sistem akan berjalan dengan baik.

**Comment by farasyidk** [comment]
itu gak ada icon keyboard..
ak kmaren coba download yg amd64, sya coba bsa normal..tpi processor sya intel, bgus egk y d.install itu??

**Comment by mnirfan** [comment]
amd64 bisa dijalankan di prosesor intel yang mendukung arsitektur 64bit. saya pribadi biasa install linux 64bit di laptop intel saya.

**Comment by farasyidk** [comment]
oke, trimakasih..
ditunggu tealinux 8 nya, :+1: :)

**Comment by mnirfan** [comment]
sama sama.
kalau bisa datang ya ke release party-nya.
info http://tealinuxos.org/release

**Comment by farasyidk** [comment]
pengen kk..
tpi sya tinggal di Imogiri, Bantul, Yogyakarta -_-
klo tdak kberatan sya krimi link download iso TeaLinuxos 8, lgsung sya instal :)

**Comment by farasyidk** [comment]
Kk tnya lg, tealinuxos sya eror stelah instal apliksi..
Jdi gni stelh booting tealnux kn hrus memsukkn pasword, bsa memilh adminstator,guest, tau other .
Nah ketika sya sudh login administator hnya muncl walpaper, tdk ad icon, menu yg ad di atas, sya mengetk sesuatu tdk b.pengarh,.tpi klo sya login sbgai GUEST, tampilnnya normal bsa untk bkak apliksi,dll.

**Comment by mnirfan** [comment]
aplikasi apa yang diinstall dan via apa installnya?

**Comment by farasyidk** [comment]
sya install aplikasi Zekr dan elforkane melalui terminal semua .

**Comment by leomanangka** [comment]
ka tealinuxOS 8 install printer canon gimana ? mohon bantuannya | TY

**Comment by mnirfan** [comment]
cannon seri apa?

**Comment by mnirfan** [comment]
@fadqur bisa dicoba dengan membuat user baru. apakah masih blank?

**Comment by mnirfan** [comment]
@Lmanangka cannon seri apa?

**Comment by mnirfan** [comment]
Harap diperhatikan, jika topik yang akan anda bahas berbeda dengan topik yang sudah ada, **mohon membuat topik/issue yang baru** untuk menjaga agar mudah terbaca. terima kasih.
