### ISSUE TITLE
Tidak bisa merubah bahasa

### ISSUE THREAD

**Issue by idbmb** [tealinuxos/lapor#11]
Saat pertama melakukan instalasi TeaLinuxOS memilih Bahasa Indonesia, Ketika sudah selesai proses instalasi dan ingin ganti bahasa ke Bahasa Inggris Tidak bisa. dikarenakan Dukungan Bahasa (Language Support) belum ada pada TealinuxOS.

Note : TeaLinuxOS 8 Peppermint (64-Bit) Build on Ubuntu 16.04

**Comment by dikyarga** [comment]
@idbmb Terimakasih atas laporanya @bambangrahmadi

**Comment by mnirfan** [comment]
Terima kasih untuk laporannya. Untuk mengganti bahasa dengan mudah:
1. pasang paket language-selector-gnome: `$ sudo apt install language-selector-gnome`
2. buka **Dukungan Bahasa** lewat menu, atau lewat terminal `gnome-language-selector`
3. tambahkan bahasa jika belum ada di daftar
4. drag n drop bahasa yang ingin dijadikan prioritas utama ke urutan paling atas
5. klik **Terapkan Sistem-Wide**
6. Logout lalu Login lagi

![dukungan-bahasa](https://cloud.githubusercontent.com/assets/9733119/22414996/8ccda63e-e6f6-11e6-9ef1-90cd1f1c6895.png)

Sudah saya coba di laptop saya dan berhasil.
Jika sudah berhasil silakan ditutup issue nya.

**Comment by idbmb** [comment]
Oke fix, Terima kasih.
