### ISSUE TITLE
Overflow pada window software dan menu editor

### ISSUE THREAD

**Issue by okyaneka** [tealinuxos/lapor#14]
terdapat warna tambahan di luar window pada box menu editor dan software
![image](https://user-images.githubusercontent.com/24471077/27043968-22c3cc30-4fc6-11e7-8b0b-041db0cc400d.png)

sama printscreennya responnya terlalu lama

**Comment by mnirfan** [comment]
Terima kasih atas laporannya. Itu 32bit atau 64bit ya?

**Comment by okyaneka** [comment]
yang 64 bit kak

2017-06-12 23:37 GMT+07:00 Nurul Irfan <notifications@github.com>:

**Comment by mnirfan** [comment]
sepertinya masalah compositornya.
coba diaktifkan lewat `Setting` > `Window Manager Tweaks` > tab `Compositor` > centang `Enable display compositing`

**Comment by okyaneka** [comment]
Oh. Makasih kak

Pada tanggal 21 Jun 2017 04:09, "Nurul Irfan" <notifications@github.com>
menulis:

**Comment by mnirfan** [comment]
Sama-sama :)
