### ISSUE TITLE
Animasi UI Box

### ISSUE THREAD

**Issue by rezafaizarahman** [tealinuxos/lapor#7]
// Ringkasan : Animasi UI Box terlalu lembut, menyebabkan aplikasi bersangkutan terkesan lambat

// Langkah : 

Minimise & maxsimise-kan jendela aplikasi. Akan terlihat UI Box seakan melambat

// Error : -

**Comment by baiquniinside** [comment]
mas reza ini ngedit e ndak yg di file compton nya??

**Comment by rezafaizarahman** [comment]
Iya, di berkas konfigurasi compton-nya, Ham.
